### ISSUE TITLE
Network traffic graphs only support wlan0

### ISSUE THREAD

**Issue by jprochazka** [jprochazka/adsb-feeder#11]
There needs to be a way to change the network traffic graph to the interface being used to cover cases where someone might be using a wired connection instead of a wireless one or a different interface than wlan0 period.

**Comment by jprochazka** [comment]
Added things needed to generate eth0 graphs as well as wlan0 graphs.
eth0 graphs are now displayed by default and wlan0 items have been commented out.

At a later time I will work on automating this by allowing the person using the scripts to choose the interface to display. Until then this issue will be "shelved" for the time being.

**Comment by mgunther68** [comment]
In make-collectd-graphs.sh it is still trying to generate wlan0 graphs by default:
system_graphs() has this line only (and nothing for eth0):
wlan0_graph /var/www/html/graphs/system-$2-wlan0_bandwidth-$4.png /var/lib/collectd/rrd/$1/interface-wlan0 "$3" "$4" "$5"

**Comment by jprochazka** [comment]
Must have commited the file from my live feeder instead of a development machine... This has been addressed with the commit ef49aca99b550328537c27f43690b8bc10fffa7c which was commited directly to the master branch.

Thanks for catching this. It's nice to have a second pair of eyes checking things out.
