### ISSUE TITLE
Add the ability to install certain items while leaving others out.

### ISSUE THREAD

**Issue by jprochazka** [jprochazka/adsb-feeder#17]
It has been requested that certain items be made installable by the scripts so they are useful to those who may have other items already installed such as a decoder or particular feeder. An option to install only the web portal is one such request. A check for dump1090-mutability will be needed however since it is a requirement for the performance graph generation. At this point it would not be a bad idea to rework the menu system as well and add the ability to trigger other installations without the need to install everything such as feeders.

This will tie into issue #5.

**Comment by mgunther68** [comment]
Thank you for looking into this and other enhancements! I'll hold off installing on my main Pi for the time being and wait how this plays out :)

**Comment by jprochazka** [comment]
Next on the list so will be starting this tonight. Would have been sooner but had another SD card burn out on my feeder so decided to switch over to using a USB drive to handle the root partition...

**Comment by jprochazka** [comment]
Commit bab50740e8d474f0cf61149b754af640d936c20d in the whiptail branch is a rough yet to be tested version of a new install.sh addressing this issue and is not yet meant for general consumption. This commit also at the same time addresses Issue #5.

* Written but not tested what so ever.
* Adds checks to see if the main ADS-B feeder packages are installed.
* Whiptail dialogs are now utilized making things much pretty, such fancy, WOW.

**Comment by jprochazka** [comment]
Added with merge. be38fdb93ac00ace3afbd719a09c6071c2daf8d1
