### ISSUE TITLE
Allow choice of imperial or metric graphs

### ISSUE THREAD

**Issue by mgunther68** [jprochazka/adsb-feeder#29]
It would be nice to have a choice for both temperature and range graphs.

**Comment by jprochazka** [comment]
This is something I need to document. The scripting is in place to make these graphs already but they have to be manually switched on. Simply comment out the following lines in the file make-collectd-graphs.sh.

    temp_graph_imperial /var/www/html/graphs/system-$2-temperature-$4.png /var/lib/collectd/rrd/$1/table-$2 "$3" "$4" "$5"
    range_graph_imperial /var/www/html/graphs/dump1090-$2-range-$4.png /var/lib/collectd/rrd/$1/dump1090-$2 "$3" "$4" "$5"

Then uncomment the following lines.

    #temp_graph_metric /var/www/html/graphs/system-$2-temperature-$4.png /var/lib/collectd/rrd/$1/table-$2 "$3" "$4" "$5"
    #range_graph_metric /var/www/html/graphs/dump1090-$2-range-$4.png /var/lib/collectd/rrd/$1/dump1090-$2 "$3" "$4" "$5"

As a side note pertaining to this issue...

I am debating on utilizing some sort of scripting language such as PHP and adding and administration area to the portal portion. Whether or not I do this will come down to how much overhead said scripting language will cost... I am going to leave this issue open for the time being until I decide on which way to go. If anything this should be added as an option during the installation.

**Comment by mgunther68** [comment]
Yes indeed I had already found where to comment/uncomment and it's working fine.

**Comment by jprochazka** [comment]
The process to enable metric graphs has been added to the wiki. However this issue will be left open pending the decision mentioned in an earlier comment regarding making a way to manage settings such as this one.

**Comment by jprochazka** [comment]
Ability to change this added into new portal administration area merged into master by pull request #68.
