### ISSUE TITLE
Links in portal page are broken

### ISSUE THREAD

**Issue by mgunther68** [jprochazka/adsb-feeder#33]
In my live and test environments (which had previously installed lighttpd), the server document root was set to: `server.document-root = "/var/www"`
However, the portal web page currently assumes that the document root is set as "/var/www/html"

The lighttpd placeholder page has this info:
*The DocumentRoot, which is the directory under which all your HTML files should exist, is set to /var/www.*

Suggest to either:
- put all html code under "/var/www" (i.e. do not create html directory under /var/www) OR
- change lighttpd config file and make `server.document-root = "/var/www/html"`

**Comment by mgunther68** [comment]
I see a comment on the flightaware discussion forum:
*Jessie changed the web server default from /var/www (in Wheezy) to /var/www/html.*

I guess that explains some of the inconsistencies I'm seeing. This issue may fall under 'legacy support'.

**Comment by jprochazka** [comment]
Right that would be what the problem is. However I will add to the script a mechanism to check if "/var/www/html" exists and if not copy files over to "/var/www/" so Wheezy based distros don't run into this problem in the future.

**Comment by mgunther68** [comment]
Or perhaps read the lighttpd config file and check for the server.document-root setting?

**Comment by jprochazka** [comment]
That would be an even better way.
This should do the trick:

    sed 's/.*"\(.*\)"[^"]*$/\1/' <<< `lighttpd -f /etc/lighttpd/lighttpd.conf -p | grep server.document-root`

**Comment by mgunther68** [comment]
Yep that works for me!

**Comment by jprochazka** [comment]
Lighttpd document root detection added in commit 74197645c88f8fcc82d58617077e2f79e681c4bd. This commit also closes issue #32.
