### ISSUE TITLE
Update PiAware to 2.1-5

### ISSUE THREAD

**Issue by dschaper** [jprochazka/adsb-feeder#36]
The piaware install script is still pulling the 2.1-3 tag, just need to update to the latest.

**Comment by jprochazka** [comment]
Beat me to it.
Thanks for the update.

**Comment by jprochazka** [comment]
Something changed during installation causing it to fail. Should have tested the script before merging the pull request. Working to get it running properly now.

**Comment by dschaper** [comment]
Hmm, tested it here and all seemed okay?

**Comment by jprochazka** [comment]
May be just my environment but it dumped out for some reason on a clean installation.

**Comment by jprochazka** [comment]
adsb-feeder/bash/feeders/piaware.sh line 132 needed updated.
    sudo dpkg -i $BUILDDIR/piaware_builder/piaware_2.1-3_*.deb
Needed changed to:
    sudo dpkg -i $BUILDDIR/piaware_builder/piaware_2.1-5_*.deb

Fix will be committed shortly after other changes have been tested.

**Comment by jprochazka** [comment]
Fix committed again thanks for pointing out the update and the contribution!
