### ISSUE TITLE
Consolidate variables located throughout the scripts.

### ISSUE THREAD

**Issue by jprochazka** [jprochazka/adsb-feeder#48]
Variables such as version numbering need to be consolidated into a single location in order to avoid confusion when updating them. Going to include the CheckPackage function while consolidating things as well.

**Comment by jprochazka** [comment]
Software versions and branch names are now located in the file ~/adsb-feeder/bash/variables.sh with commit 327bff4722e4cc10f81f3d2d9a3ab7fd246059cc.

**Comment by dschaper** [comment]
Things look okay for the most part on the cleanup branch. Did run into `/home/dan/adsb-feeder/bash/portal/install.sh: line 60: CheckPackage: command not found` setting up the portal.

**Comment by jprochazka** [comment]
Actually testing things out now. Just committed a fix for that.

**Comment by dschaper** [comment]
Test okay here...

**Comment by jprochazka** [comment]
Merged with pull request #55.
