### ISSUE TITLE
Apt-get update is run even if user declines.

### ISSUE THREAD

**Issue by dschaper** [jprochazka/adsb-feeder#52]
It appears that apt-get is run to update repositories and PPA's even if the user declines when presented the option in the whiptail dialog.

**Comment by jprochazka** [comment]
This is on purpose so that the PPA's are updated before installing prerequisite packages. System updates however are not installed unless the user chooses yes to this option.

**Comment by dschaper** [comment]
Ah, okay, so apt-get update is run automatically, but apt-get upgrade is dependent upon the user input?

**Comment by jprochazka** [comment]
You got it! I have encountered problems relating to being unable to find packages when installing packages especially on new installations where apt-get update had never been ran hence the reason I did that..

**Comment by dschaper** [comment]
I actually forgot to run raspi-config and expand the card on a fresh Jessie Lite install, so I now understand the logic behind the process! lol...
