### ISSUE TITLE
Allow altitude specification for heywhatsthat rings during dump1090 installation 

### ISSUE THREAD

**Issue by mgunther68** [jprochazka/adsb-feeder#61]
It would be nice to have a choice for the heywhatsthat rings. Personally, I'm using 30000 and 40000 feet. This is because I mostly see high-altitude trans-atlantic traffic and I'm not interested in a 10000 foot ring as I have no local traffic at that altitude.

**Comment by jprochazka** [comment]
This should not be too hard to accomplish. Look for options to be added to the dump1090 setup script shortly.

**Comment by jprochazka** [comment]
Ability to specify range add with commit 4830a31dfd78a799b92ef78aa066703fb162e577.
