### ISSUE TITLE
Add graph for messages per aircraft per second

### ISSUE THREAD

**Issue by mgunther68** [jprochazka/adsb-feeder#63]
A graph like this could be a useful aid in testing antenna/filter/amplifier performance. The aim would be to achieve a high message per a/c per second rate.

A sample graph could look like this:
msg_sec_ac_graph() {
  rrdtool graph \
  "$1" \
  --start end-$4 \
  --width 480 \
  --height 200 \
  --step "$5" \
  --title "$3 Message Rate / AC / Second" \
  --vertical-label "Rate/AC/Second" \
  --lower-limit 0 \
  --units-exponent 0 \
  "TEXTALIGN:center" \
  "DEF:all=$2/dump1090_aircraft-recent.rrd:total:AVERAGE" \
  "DEF:messages=$2/dump1090_messages-local_accepted.rrd:value:AVERAGE" \
  "CDEF:rate=messages,all,/" \
  "VDEF:avgrate=rate,AVERAGE" \
  "VDEF:maxrate=rate,MAXIMUM" \
  "GPRINT:avgrate:Average\:%3.0lf " \
  "GPRINT:maxrate:Maximum\:%3.0lf " \
  "LINE1:all#990000:A/C" \
  "LINE1:rate#0000FF:Rate" \
  "LINE1:maxrate#FF0000:Max Rate" \
  "LINE1:avgrate#666666:Avg Rate:dashes" \
  --watermark "Drawn: $nowlit";
}

**Comment by jprochazka** [comment]
Will add this graph to the admin branch as soon as I fix the Boolean issue.

**Comment by jprochazka** [comment]
Graph added in commit 358e955c54cbdc2b882452177efac6c35b13cc75. However the new graph has not been tested yet due to the fact I do not have access to a working dump1090 device at the moment.

**Comment by mgunther68** [comment]
Let me know if/how I can help with testing. I'll have access to my secondary Pi later this evening.

**Comment by jprochazka** [comment]
Installation information is here: http://discussions.flightaware.com/post187558.html#p187558
May be some issues it is not tested on a RTL-SDR equipped device. Will be testing it out tonight on a proper device tonight as well.

**Comment by jprochazka** [comment]
Graph added to the portal and merged into master by pull request #68.
