### ISSUE TITLE
Standardise graph image sizes

### ISSUE THREAD

**Issue by mgunther68** [jprochazka/adsb-feeder#66]
In make-collectd-graphs.sh, when specifying the graph size like this: `  --width 480 \
  --height 200 \
`, this applies to the actual graph image only. Any titles, axis text and legend text add to the overall image size. Graph definitions should be standardised so that the final images are all of equal size; this will lead to a more uniform and even display of graphs on the Performance Graphs page. The aim should be to show identical output sizes when running make-collectd-graphs.sh manually. I suggest a standard size of 577x298 pixels. This is a normal graph defined as 480x200 plus title, one axis with description, two lines of legend and the watermark. Where a graph has a right-hand axis plus text, the width of the actual graph should be reduced to achieve a final image width of 577 pixels.

Please let me know if you want me to work on this with the currently defined graphs or if you plan to re-work the graphs in the near future and will take care of this at that stage.

**Comment by mgunther68** [comment]
That's done now with my recent pull requests.

**Comment by jprochazka** [comment]
Noted and thanks for the commits.
