### ISSUE TITLE
dump1090 collectd: No such file or directory

### ISSUE THREAD

**Issue by paranoidjack** [jprochazka/adsb-feeder#77]
Using the latest revision (1/2/2016) the dump1090 graphs aren't generating. System graphs are generated without a problem.

When running the cron manually this is the error:

```
root@T-EGAC20:/opt/adsb-feeder# bash /opt/adsb-feeder/build/portal/graphs/make-collectd-graphs.sh 1h
2583 (process ID) old priority 0, new priority 5
ERROR: opening '/var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_aircraft-recent.rrd': No such file or directory
ERROR: opening '/var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_aircraft-recent.rrd': No such file or directory
ERROR: opening '/var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_cpu-demod.rrd': No such file or directory
ERROR: opening '/var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_tracks-all.rrd': No such file or directory
1107x284
577x298
577x298
577x298
577x298
577x298
577x298
577x298
ERROR: opening '/var/lib/collectd/rrd/localhost/interface-wlan0/if_octets.rrd': No such file or directory
ERROR: opening '/var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_messages-local_accepted.rrd': No such file or directory
ERROR: opening '/var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_messages-local_accepted.rrd': No such file or directory
ERROR: opening '/var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_range-max_range.rrd': No such file or directory
ERROR: opening '/var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_range-max_range.rrd': No such file or directory
ERROR: opening '/var/lib/collectd/rrd/localhost/dump1090-localhost/dump1090_dbfs-signal.rrd': No such file or directory

```

**Comment by mgunther68** [comment]
This sounds more like an issue with dump1090-mutability not producing rrd files. What do you have here?
~ $ ls -l /var/lib/collectd/rrd/localhost/dump1090-localhost/

Is dump1090-mutability running fine?

**Comment by paranoidjack** [comment]
dump1090-mutability is working perfectly fine and I can track aircraft through it's live map. 

The folder (/var/lib/collectd/rrd/localhost/dump1090-localhost/) doesn't exist and doesn't seem to have been created during the set-up procedure. I used the script just last week without any issues so the problem may of arisen within last couple of commits. 

However, I'll rerun the script today just to confirm it wasn't a glitch.

**Comment by paranoidjack** [comment]
So I've tracked the problem down to the collectd service failing to start:

Feb 03 16:16:39 DietPi systemd[1]: Started LSB: manage the statistics collection daemon.
Feb 03 16:16:40 DietPi collectd[462]: lt_dlopen ("/usr/lib/collectd/python.so") failed: file not found. The most common cause for this problem are missing depende...red object.
Feb 03 16:16:40 DietPi collectd[462]: plugin_load: Load plugin "python" failed with status 1.
Feb 03 16:16:40 DietPi collectd[462]: Found a configuration for the `python' plugin, but the plugin isn't loaded or didn't register a configuration callback.
Feb 03 16:16:40 DietPi collectd[462]: Found a configuration for the `python' plugin, but the plugin isn't loaded or didn't register a configuration callback.
Feb 03 16:16:40 DietPi collectd[462]: Found a configuration for the `python' plugin, but the plugin isn't loaded or didn't register a configuration callback.
Feb 03 16:16:40 DietPi collectd[462]: There is a `Module' block within the configuration for the python plugin. The plugin either only expects "simple" configurat...figuration.
Feb 03 16:16:40 DietPi collectd[462]: Initialization complete, entering read-loop.
Feb 03 16:16:40 DietPi collectd[462]: rrdtool plugin: Adjusting "RandomTimeout" to 0.000 seconds.

It seems that libpython2.7 isn't being installed which is a dependency for /usr/lib/collectd/python.so - installing that library and rerunning the portal installer fixes this issue.

**Comment by mgunther68** [comment]
Do the install scripts check for libpython2.7? If not, should this issue be re-opened and a check added for libpython2.7?

**Comment by jprochazka** [comment]
Adding a check for the libpython2.7 package. Testing things out to make sure it does not cause issues on mainstream distros such as Debian before committing it.

**Comment by jprochazka** [comment]
Everything checked out added the check in commit 98bd5b7ab165ae23dfce87f1d49600b5a5f96416.
Good idea mgunther68.
